### ISSUE TITLE
The problem about the third step:Download Dependancy

### ISSUE THREAD

**Issue by tangyuhao2016** [mczhuge/Kaleido-BERT#1]
Thank you for sharing such great work.

When I run the  sh get_checkpoint.sh, I get the mistake like below:

Resolving icbu-ensa-sc.oss-cn-zhangjiakou.aliyuncs.com (icbu-ensa-sc.oss-cn-zhangjiakou.aliyuncs.com)... 47.92.17.218
Connecting to icbu-ensa-sc.oss-cn-zhangjiakou.aliyuncs.com (icbu-ensa-sc.oss-cn-zhangjiakou.aliyuncs.com)|47.92.17.218|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden.

And when I click the link directly, I get the mistake like below:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>You have no right to access this object because of bucket acl.</Message>
<RequestId>607C319BB6DA383338EC6AFD</RequestId>
<HostId>icbu-ensa-sc.oss-cn-zhangjiakou.aliyuncs.com</HostId>
</Error>

May you provide the solution?

**Comment by mczhuge** [comment]
Hi,  Yuhao,
    Thank you for informing this error,  I feel sorry about this mistake.
    I have repaired the shell file get_checkpoint.sh, please modified it according to https://github.com/mczhuge/Kaleido-BERT/blob/main/scripts/checkpoint/get_checkpoint.sh and try it again.
    Best regards.

**Comment by tangyuhao2016** [comment]
Thank you for your help, the problem has been solved.
However, the download speed is so slow, I have tried several times and different networks are used. It's only tens of K per second, and it's very easy to interrupt.
Could you upload the source data to the Baidu cloud disk or Google cloud disk?

**Comment by mczhuge** [comment]
Since the limits of authority, we cannot directly put these data in Baidu or Google disk right now. 
But there may have two solutions:

1) First, you can download these datasets by Xunlei or some other similar tools.  I just copy the links to Xunlei, such as http://icbu-ensa-sc.oss-cn-zhangjiakou.aliyuncs.com/mingchen.zgmc/KaleidoBERT_TF_CODE/datasets/checkpoint/kaleidobert.ckpt-50683.data-00000-of-00001, and the download speed can achieve 10MB/s.
2) Waiting for Alibaba Disk ^_^

I wish it could be helpful for you.

**Comment by tangyuhao2016** [comment]
Thank you for your help. Even though I use Xunlei with the vip, the speed is only 200-300k/s. And the FashionGen dataset is very large, one download link is about 16.5g and there are several links.

**Comment by mczhuge** [comment]
Yes. The pre-processed datasets are large. 
I did not use the Xunlei VIP but also get a 7MB/s download speed. 
Can you add my WeChat? ID: tjpxiaoming
