### ISSUE TITLE
When will the PyTorch version code be released？

### ISSUE THREAD

**Issue by AwellmanZha** [mczhuge/Kaleido-BERT#10]
Thanks! When will the PyTorch version code be released？

**Comment by mczhuge** [comment]
Hi, Maxi. We will release a version using PyTorch recently, the related paper has been submitted to ICML2022. Best.

**Comment by DengPingFan** [comment]
Hi, 

Please check our new version

The paper link: https://dengpingfan.github.io/papers/[2022][MIR]MVLT.pdf
Code: https://github.com/GewelsJI/MVLT

Best,
