### ISSUE TITLE
Request for the PyTorch version

### ISSUE THREAD

**Issue by tymanman** [mczhuge/Kaleido-BERT#11]
Hi,Have u been ready to share the PyTorch version of this work?thank u.

**Comment by mczhuge** [comment]
Hi, Maxi. We will release a version using PyTorch recently, the related paper has been submitted to ICML2022. Best.

**Comment by DengPingFan** [comment]
Hi, 

Please check our new version.

The paper link: https://dengpingfan.github.io/papers/[2022][MIR]MVLT.pdf
Code: https://github.com/GewelsJI/MVLT

Best,
