### ISSUE TITLE
Release Pytorch version

### ISSUE THREAD

**Issue by BrandonHanx** [mczhuge/Kaleido-BERT#7]
Hi, thanks for your excellent work!

I was wondering when would you release the Pytorch version. I think it will benefit downstream tasks a lot.

**Comment by mczhuge** [comment]
I have left the previous company. I will do this work as soon as possible when I get a NEW job. Very sorry for delaying!

**Comment by tymanman** [comment]
Thanks for your work! Do u have a plan to continue on the PyTorch version of this repo?

**Comment by DengPingFan** [comment]
Hi, 

Please check our new version.

The paper link: https://dengpingfan.github.io/papers/[2022][MIR]MVLT.pdf
Code: https://github.com/GewelsJI/MVLT

Best,
