### ISSUE TITLE
Finetuning of Kaleido-BERT for Fashion Captioning Update

### ISSUE THREAD

**Issue by gourango01** [mczhuge/Kaleido-BERT#8]
#6 
During the fine-tuning on the image captioning task, Did you use any pre-training task (for e.g., AKPM, TIM and AMLM) along with the fashion captioning task i.e., given an image ( i.e., sequence of image patches generated by "Kaleido Patch Generator") predict the corresponding caption?

**Comment by mczhuge** [comment]
no, just input the image feature
