### ISSUE TITLE
预处理

### ISSUE THREAD

**Issue by Ji-Mingkuo** [mczhuge/Kaleido-BERT#9]
请问可以开放一下图文预处理模块、token对齐模块吗？

**Comment by mczhuge** [comment]
1. 近期会把图像部分预处理release
2. 文本预处理请参考[bert tokenizer](https://github.com/google-research/bert/blob/master/tokenization.py)
3. 对齐模块利用在电商数据集上重训练的SAT网络产生热力图，并以此为依据粗糙的对齐image patch和word token。生成的对齐很粗糙，近期我们在想办法设计更为实用的对齐模块。
